name: Build KivyMD APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ تثبيت Java 17
      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_PATH
          java -version

      # ✅ تثبيت Buildozer ومتطلباته
      - name: Install Buildozer dependencies
        run: |
          sudo apt install -y python3-pip unzip wget libffi-dev libssl-dev
          pip3 install --upgrade pip
          pip3 install buildozer cython virtualenv

      # ✅ تثبيت Android SDK و Build-Tools مع القبول التلقائي للترخيص
      - name: Install Android SDK and build-tools
        run: |
          export ANDROID_HOME=$HOME/.android/sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip
          mv cmdline-tools latest
          
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;33.0.2"

      # ✅ إصلاح مسار AIDL يدويًا
      - name: Fix AIDL Path
        run: |
          export ANDROID_HOME=$HOME/.android/sdk
          export BUILD_FOLDER=$HOME/.buildozer/android/platform/android-sdk

          mkdir -p "$BUILD_FOLDER/build-tools/33.0.2"
          ln -sf "$ANDROID_HOME/build-tools/33.0.2/aidl" "$BUILD_FOLDER/build-tools/33.0.2/aidl"

          echo "Fixed AIDL path."

      # ✅ تشغيل Buildozer لإنشاء ملف APK
      - name: Build APK
        run: |
          buildozer -v android debug

      # ✅ رفع ملف APK كـ Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KivyMD-App
          path: project-1/bin/*.apk
