name: Build KivyMD APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ تنزيل الكود من المستودع
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ تثبيت Java 17
      - name: Install Java 17
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "/usr/lib/jvm/java-17-openjdk-amd64/bin" >> $GITHUB_PATH
          java -version

      # ✅ تثبيت Buildozer ومتطلباته
      - name: Install Buildozer dependencies
        run: |
          sudo apt install -y python3-pip unzip wget
          pip3 install --upgrade pip
          pip3 install buildozer cython

      # ✅ تثبيت Android SDK و Build-Tools
      - name: Install Android SDK and build-tools
        run: |
          export ANDROID_HOME=$HOME/.android/sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk-tools.zip
          unzip sdk-tools.zip
          mv cmdline-tools latest
          
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-31" "build-tools;33.0.2"

      # ✅ إصلاح مسار SDK Manager داخل Buildozer
      - name: Fix SDK Manager Path for Buildozer
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin
          ln -sf $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager
          echo "Fixed SDK Manager path."

      # ✅ إصلاح مسار Build-Tools داخل Buildozer
      - name: Fix Build-Tools Path
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/build-tools/33.0.2
          ln -sf $ANDROID_HOME/build-tools/33.0.2/aidl ~/.buildozer/android/platform/android-sdk/build-tools/33.0.2/aidl
          echo "Fixed Build-Tools path."

      # ✅ التحقق من `sdkmanager`
      - name: Verify SDK Manager
        run: |
          if [ ! -f "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" ]; then
            echo "❌ SDK Manager is missing!"
            exit 1
          else
            echo "✅ SDK Manager found!"
          fi

      # ✅ تشغيل Buildozer لإنشاء ملف APK
      - name: Build APK
        run: |
          buildozer -v android debug

      # ✅ رفع ملف APK كـ Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KivyMD-App
          path: project-1/bin/*.apk
